export const campaigns = [
  {
    id: 1,
    title: 'Summer Sale 2024',
    brand: 'BrandLab',
    image: null,
    status: 'inProgress',
    statusLabel: 'W trakcie',
    creators: {
      current: 8,
      total: 12,
    },
    progress: 67,
    avatars: [
      null,
      null,
      null,
      null,
    ],
    extraCreators: 3,
    messagesCount: 5,
    gradient: 'from-[#784DFF] to-[#A78BFA]',
  },
  {
    id: 2,
    title: 'New Collection Launch',
    brand: 'StyleStore',
    image: null,
    status: 'inProgress',
    statusLabel: 'W trakcie',
    creators: {
      current: 6,
      total: 8,
    },
    progress: 75,
    avatars: [
      null,
      null,
      null,
    ],
    extraCreators: 1,
    messagesCount: 3,
    gradient: 'from-[#0EA5E9] to-[#67E8F9]',
  },
  {
    id: 3,
    title: 'Black Friday 2024',
    brand: 'EvoShop',
    image: null,
    status: 'planned',
    statusLabel: 'Planowana',
    creators: {
      current: 0,
      total: 10,
    },
    progress: 0,
    avatars: [
      null,
      null,
      null,
    ],
    extraCreators: 5,
    messagesCount: 0,
    gradient: 'from-[#EF4444] to-[#F97316]',
  },
  {
    id: 4,
    title: 'Back to School',
    brand: 'BrandLab',
    image: null,
    status: 'inProgress',
    statusLabel: 'W trakcie',
    creators: {
      current: 7,
      total: 7,
    },
    progress: 100,
    avatars: [
      null,
      null,
      null,
      null,
    ],
    extraCreators: 0,
    messagesCount: 2,
    gradient: 'from-[#22C55E] to-[#86EFAC]',
  },
]