export const campaignsResponse = {
  totalItems: 97,
  totalPages: 20,
  currentPage: 1,
  itemsPerPage: 5,
  campaigns: [
    {
      id: 'cmp_001',
      title: 'Summer Sale 2024',
      brand: 'BrandLab',
      imageUrl: '/images/campaigns/summer-sale-2024.png',
      status: 'inProgress',
      platforms: ['Instagram', 'TikTok'],
      budget: {
        amount: null,
        currency: 'PLN',
        hidden: true,
      },
      guardian: {
        id: 'usr_001',
        name: 'Ty',
        avatarUrl: '/images/avatars/user.png',
        isCurrentUser: true,
      },
      creators: {
        current: 12,
        total: 15,
      },
      tasks: {
        current: 26,
        total: 40,
      },
      progress: 65,
      reach: {
        total: 1200000,
        formatted: '1.2M',
      },
      dates: {
        createdAt: '2024-05-15T00:00:00.000Z',
        updatedAt: '2024-05-24T11:30:00.000Z',
        startsAt: null,
        endedAt: null,
      },
    },
    {
      id: 'cmp_002',
      title: 'New Collection Launch',
      brand: 'StyleStore',
      imageUrl: '/images/campaigns/new-collection.png',
      status: 'inProgress',
      platforms: ['Instagram'],
      budget: {
        amount: 25000,
        currency: 'PLN',
        hidden: false,
      },
      guardian: {
        id: 'usr_002',
        name: 'Anna Kowalska',
        avatarUrl: '/images/avatars/anna.png',
        isCurrentUser: false,
      },
      creators: {
        current: 8,
        total: 10,
      },
      tasks: {
        current: 18,
        total: 30,
      },
      progress: 60,
      reach: {
        total: 850000,
        formatted: '850K',
      },
      dates: {
        createdAt: '2024-05-02T00:00:00.000Z',
        updatedAt: '2024-05-23T15:42:00.000Z',
        startsAt: null,
        endedAt: null,
      },
    },
    {
      id: 'cmp_003',
      title: 'Black Friday 2024',
      brand: 'EvoShop',
      imageUrl: '/images/campaigns/black-friday-2024.png',
      status: 'inProgress',
      platforms: ['Instagram', 'TikTok', 'YouTube'],
      budget: {
        amount: 40000,
        currency: 'PLN',
        hidden: false,
      },
      guardian: {
        id: 'usr_001',
        name: 'Ty',
        avatarUrl: '/images/avatars/user.png',
        isCurrentUser: true,
      },
      creators: {
        current: 20,
        total: 25,
      },
      tasks: {
        current: 32,
        total: 60,
      },
      progress: 53,
      reach: {
        total: 2100000,
        formatted: '2.1M',
      },
      dates: {
        createdAt: '2024-04-10T00:00:00.000Z',
        updatedAt: '2024-05-21T00:00:00.000Z',
        startsAt: null,
        endedAt: null,
      },
    },
    {
      id: 'cmp_004',
      title: 'Back to School',
      brand: 'BrandLab',
      imageUrl: '/images/campaigns/back-to-school.png',
      status: 'planned',
      platforms: ['Instagram', 'TikTok'],
      budget: {
        amount: 18000,
        currency: 'PLN',
        hidden: false,
      },
      guardian: {
        id: 'usr_003',
        name: 'Michał Nowak',
        avatarUrl: '/images/avatars/michal.png',
        isCurrentUser: false,
      },
      creators: {
        current: 5,
        total: 8,
      },
      tasks: {
        current: 0,
        total: 20,
      },
      progress: 0,
      reach: {
        total: null,
        formatted: null,
      },
      dates: {
        createdAt: '2024-05-20T00:00:00.000Z',
        updatedAt: null,
        startsAt: '2024-08-01T00:00:00.000Z',
        endedAt: null,
      },
    },
    {
      id: 'cmp_005',
      title: 'Spring Collection 2024',
      brand: 'StyleStore',
      imageUrl: '/images/campaigns/spring-collection-2024.png',
      status: 'closed',
      platforms: ['Instagram'],
      budget: {
        amount: 20000,
        currency: 'PLN',
        hidden: false,
      },
      guardian: {
        id: 'usr_002',
        name: 'Anna Kowalska',
        avatarUrl: '/images/avatars/anna.png',
        isCurrentUser: false,
      },
      creators: {
        current: 10,
        total: 10,
      },
      tasks: {
        current: 30,
        total: 30,
      },
      progress: 100,
      reach: {
        total: 1800000,
        formatted: '1.8M',
      },
      dates: {
        createdAt: '2024-03-15T00:00:00.000Z',
        updatedAt: null,
        startsAt: null,
        endedAt: '2024-04-30T00:00:00.000Z',
      },
    },
     {
      id: 'cmp_006',
      title: 'Winter Collection 2025',
      brand: 'StyleStore',
      imageUrl: '/images/campaigns/Winter-collection-2025.png',
      status: 'closed',
      platforms: ['Instagram'],
      budget: {
        amount: 25000,
        currency: 'PLN',
        hidden: false,
      },
      guardian: {
        id: 'usr_002',
        name: 'Anna Kowalska',
        avatarUrl: '/images/avatars/anna.png',
        isCurrentUser: false,
      },
      creators: {
        current: 10,
        total: 10,
      },
      tasks: {
        current: 30,
        total: 30,
      },
      progress: 100,
      reach: {
        total: 1800000,
        formatted: '1.8M',
      },
      dates: {
        createdAt: '2024-03-15T00:00:00.000Z',
        updatedAt: null,
        startsAt: null,
        endedAt: '2024-04-30T00:00:00.000Z',
      },
    },
  ],
}