export const tasks = [
  {
    id: 1,
    title: 'Prześlij brief dla 3 twórców',
    campaign: 'New Collection Launch',
    status: 'todo',
    statusLabel: 'Do zrobienia',
    priority: 'high',
    priorityLabel: 'Wysoki',
    dueDate: 'Dziś, 13:00',
    completed: false,
  },
  {
    id: 2,
    title: 'Zweryfikuj content od 2 twórców',
    campaign: 'Back to School',
    status: 'todo',
    statusLabel: 'Do zrobienia',
    priority: 'medium',
    priorityLabel: 'Średni',
    dueDate: 'Jutro, 10:00',
    completed: false,
  },
  {
    id: 3,
    title: 'Dodaj 5 nowych twórców do bazy',
    campaign: 'Black Friday 2024',
    status: 'todo',
    statusLabel: 'Do zrobienia',
    priority: 'low',
    priorityLabel: 'Niski',
    dueDate: 'Jutro, 14:00',
    completed: false,
  },
  {
    id: 4,
    title: 'Odpowiedz na wiadomości od twórców',
    campaign: 'Summer Sale 2024',
    status: 'inProgress',
    statusLabel: 'W trakcie',
    priority: 'high',
    priorityLabel: 'Wysoki',
    dueDate: 'Dziś, 11:00',
    completed: false,
  },
  {
    id: 5,
    title: 'Ustal szczegóły współpracy',
    campaign: 'Summer Sale 2024',
    status: 'todo',
    statusLabel: 'Do zrobienia',
    priority: 'medium',
    priorityLabel: 'Średni',
    dueDate: 'Dziś, 15:00',
    completed: false,
  },
  {
    id: 6,
    title: 'Sprawdź statystyki kampanii',
    campaign: 'Back to School',
    status: 'inProgress',
    statusLabel: 'W trakcie',
    priority: 'low',
    priorityLabel: 'Niski',
    dueDate: 'Piątek, 09:00',
    completed: false,
  },
  {
    id: 7,
    title: 'Przygotuj raport dla klienta',
    campaign: 'Black Friday 2024',
    status: 'closed',
    statusLabel: 'Zakończone',
    priority: 'medium',
    priorityLabel: 'Średni',
    dueDate: 'Poniedziałek, 12:00',
    completed: true,
  },
  {
    id: 8,
    title: 'Zamknij kampanię testową',
    campaign: 'New Collection Launch',
    status: 'closed',
    statusLabel: 'Zakończone',
    priority: 'low',
    priorityLabel: 'Niski',
    dueDate: 'Wczoraj, 16:00',
    completed: true,
  },
]